# Generated by Django 5.2.7 on 2025-10-28 01:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HpTrakcare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_familia", models.CharField(blank=True, max_length=100)),
                ("relacion_parentezco", models.CharField(blank=True, max_length=100)),
                ("id_trakcare", models.CharField(blank=True, max_length=100)),
                ("etnia", models.CharField(blank=True, max_length=100)),
                ("cod_registro", models.CharField(blank=True, max_length=100)),
                ("nacionalidad", models.CharField(blank=True, max_length=100)),
                ("run", models.CharField(blank=True, db_index=True, max_length=12)),
                ("ap_paterno", models.CharField(blank=True, max_length=255)),
                ("ap_materno", models.CharField(blank=True, max_length=255)),
                ("nombre", models.CharField(blank=True, max_length=255)),
                ("genero", models.CharField(blank=True, max_length=20)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("edad", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("telefono_celular", models.CharField(blank=True, max_length=30)),
                ("telefono_recado", models.CharField(blank=True, max_length=30)),
                ("servicio_salud", models.CharField(blank=True, max_length=255)),
                ("centro_inscripcion", models.CharField(blank=True, max_length=255)),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("prevision", models.CharField(blank=True, max_length=100)),
                ("plan_trakcare", models.CharField(blank=True, max_length=100)),
                ("prais_trakcare", models.CharField(blank=True, max_length=100)),
                ("fecha_incorporacion", models.DateField(blank=True, null=True)),
                ("fecha_ultima_modif", models.DateField(blank=True, null=True)),
                ("fecha_defuncion", models.DateField(blank=True, null=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "ordering": ["run", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CorteFonasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run", models.CharField(db_index=True, max_length=12)),
                ("nombres", models.CharField(blank=True, max_length=255)),
                ("ap_paterno", models.CharField(blank=True, max_length=255)),
                ("ap_materno", models.CharField(blank=True, max_length=255)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("genero", models.CharField(blank=True, max_length=20)),
                ("tramo", models.CharField(blank=True, max_length=50)),
                ("fecha_corte", models.DateField()),
                ("cod_genero", models.CharField(blank=True, max_length=50)),
                ("nombre_centro", models.CharField(blank=True, max_length=255)),
                ("motivo", models.CharField(blank=True, max_length=255)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_corte", "run"],
                "unique_together": {("run", "fecha_corte")},
            },
        ),
    ]
