# Generated by Django 5.2.7 on 2025-10-29 14:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidacionCorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_mes", models.PositiveSmallIntegerField()),
                ("periodo_anio", models.PositiveSmallIntegerField()),
                ("fecha_corte", models.DateField()),
                ("total_usuarios", models.PositiveIntegerField(default=0)),
                ("usuarios_validados", models.PositiveIntegerField(default=0)),
                ("usuarios_no_validados", models.PositiveIntegerField(default=0)),
                ("usuarios_pendientes", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "procesado_el",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("procesado_por", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-periodo_anio", "-periodo_mes"],
                "unique_together": {("periodo_anio", "periodo_mes", "fecha_corte")},
            },
        ),
        migrations.CreateModel(
            name="NuevoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run", models.CharField(db_index=True, max_length=12)),
                ("nombre_completo", models.CharField(max_length=500)),
                ("fecha_solicitud", models.DateField()),
                ("periodo_mes", models.PositiveSmallIntegerField()),
                ("periodo_anio", models.PositiveSmallIntegerField()),
                ("nacionalidad", models.CharField(blank=True, max_length=100)),
                ("etnia", models.CharField(blank=True, max_length=100)),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("subsector", models.CharField(blank=True, max_length=100)),
                ("codigo_percapita", models.CharField(blank=True, max_length=50)),
                ("establecimiento", models.CharField(blank=True, max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("VALIDADO", "Validado"),
                            ("NO_VALIDADO", "No Validado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
                ("creado_por", models.CharField(blank=True, max_length=100)),
                (
                    "validacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nuevos_usuarios",
                        to="api.validacioncorte",
                    ),
                ),
            ],
            options={
                "ordering": ["-periodo_anio", "-periodo_mes", "fecha_solicitud"],
                "indexes": [
                    models.Index(
                        fields=["periodo_anio", "periodo_mes"],
                        name="api_nuevous_periodo_774079_idx",
                    ),
                    models.Index(
                        fields=["estado"], name="api_nuevous_estado_17a2df_idx"
                    ),
                    models.Index(
                        fields=["run", "periodo_anio", "periodo_mes"],
                        name="api_nuevous_run_1d53ee_idx",
                    ),
                ],
            },
        ),
    ]
