# Generated by Django 5.2.7 on 2025-10-29 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_validacioncorte_nuevousuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ETNIA", "Etnia"),
                            ("NACIONALIDAD", "Nacionalidad"),
                            ("SECTOR", "Sector"),
                            ("SUBSECTOR", "Subsector"),
                            ("ESTABLECIMIENTO", "Establecimiento"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("codigo", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Catálogos",
                "ordering": ["tipo", "orden", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "activo"], name="api_catalog_tipo_436618_idx"
                    )
                ],
                "unique_together": {("tipo", "nombre")},
            },
        ),
    ]
