# Generated by Django 5.2.3 on 2025-10-29 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_catalogo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogo",
            options={
                "ordering": ["tipo", "orden", "nombre"],
                "verbose_name": "Catálogo",
                "verbose_name_plural": "Catálogos",
            },
        ),
        migrations.AlterField(
            model_name="catalogo",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="catalogo",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name="HistorialCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_carga",
                    models.CharField(
                        choices=[
                            ("CORTE_FONASA", "Corte FONASA"),
                            ("HP_TRAKCARE", "HP Trakcare"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=500)),
                ("usuario", models.CharField(max_length=255)),
                (
                    "fecha_carga",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "periodo_mes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "periodo_anio",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("fecha_corte", models.DateField(blank=True, null=True)),
                ("total_registros", models.PositiveIntegerField(default=0)),
                ("registros_creados", models.PositiveIntegerField(default=0)),
                ("registros_actualizados", models.PositiveIntegerField(default=0)),
                ("registros_invalidos", models.PositiveIntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EXITOSO", "Exitoso"),
                            ("ERROR", "Error"),
                            ("PARCIAL", "Parcial"),
                        ],
                        default="EXITOSO",
                        max_length=20,
                    ),
                ),
                ("reemplazo", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True)),
                ("tiempo_procesamiento", models.FloatField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Historial de Carga",
                "verbose_name_plural": "Historial de Cargas",
                "ordering": ["-fecha_carga"],
                "indexes": [
                    models.Index(
                        fields=["tipo_carga", "-fecha_carga"],
                        name="api_histori_tipo_ca_4a7aed_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-fecha_carga"],
                        name="api_histori_usuario_1f2bfb_idx",
                    ),
                    models.Index(
                        fields=["periodo_anio", "periodo_mes"],
                        name="api_histori_periodo_569a71_idx",
                    ),
                ],
            },
        ),
    ]
