# Generated by Django 5.2.3 on 2025-10-29 20:00

from typing import Optional

from django.db import migrations, models


REPLACEMENTS = {
    "Á": "A",
    "À": "A",
    "Â": "A",
    "Ä": "A",
    "Ã": "A",
    "É": "E",
    "È": "E",
    "Ê": "E",
    "Ë": "E",
    "Í": "I",
    "Ì": "I",
    "Î": "I",
    "Ï": "I",
    "Ó": "O",
    "Ò": "O",
    "Ô": "O",
    "Ö": "O",
    "Õ": "O",
    "Ú": "U",
    "Ù": "U",
    "Û": "U",
    "Ü": "U",
    "Ñ": "N",
    "Ç": "C",
    "�": "O",
}


def normalize(value: Optional[str]) -> str:
    if not value:
        return ""

    normalized = value.upper()
    for source, target in REPLACEMENTS.items():
        normalized = normalized.replace(source, target)

    while "  " in normalized:
        normalized = normalized.replace("  ", " ")

    return normalized.strip()


def forward_populate(apps, schema_editor):
    CorteFonasa = apps.get_model("api", "CorteFonasa")
    batch = []

    for corte in CorteFonasa.objects.all().iterator(chunk_size=1000):
        normalized = normalize(corte.motivo)
        if corte.motivo_normalizado != normalized:
            corte.motivo_normalizado = normalized
            batch.append(corte)
        if len(batch) >= 1000:
            CorteFonasa.objects.bulk_update(batch, ["motivo_normalizado"])
            batch.clear()

    if batch:
        CorteFonasa.objects.bulk_update(batch, ["motivo_normalizado"])


def reverse_populate(apps, schema_editor):
    CorteFonasa = apps.get_model("api", "CorteFonasa")
    CorteFonasa.objects.all().update(motivo_normalizado="")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_catalogo_options_alter_catalogo_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cortefonasa",
            name="motivo_normalizado",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.RunPython(forward_populate, reverse_populate),
    ]
