# Generated by Django 5.2.7 on 2025-10-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_cortefonasa_motivo_normalizado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ETNIA", "Etnia"),
                    ("NACIONALIDAD", "Nacionalidad"),
                    ("SECTOR", "Sector"),
                    ("SUBSECTOR", "Subsector"),
                    ("ESTABLECIMIENTO", "Establecimiento"),
                    ("CENTRO", "Centro"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
