# Generated by Django 5.2.3 on 2025-10-31 05:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_catalogo_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroSalud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
                ("tipo", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Centro de Salud",
                "verbose_name_plural": "Centros de Salud",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        help_text="CESFAM, Hospital, Consultorio, etc.",
                        max_length=100,
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=500)),
                ("comuna", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Establecimiento",
                "verbose_name_plural": "Establecimientos",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Etnia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Etnia",
                "verbose_name_plural": "Etnias",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Nacionalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
                (
                    "codigo_pais",
                    models.CharField(
                        blank=True, help_text="Código ISO 3166-1 alpha-3", max_length=3
                    ),
                ),
            ],
            options={
                "verbose_name": "Nacionalidad",
                "verbose_name_plural": "Nacionalidades",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color en formato hexadecimal #RRGGBB",
                        max_length=7,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectores",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subsector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color en formato hexadecimal #RRGGBB",
                        max_length=7,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsector",
                "verbose_name_plural": "Subsectores",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Catalogo",
        ),
        migrations.AlterModelOptions(
            name="cortefonasa",
            options={
                "ordering": ["-fecha_corte", "run"],
                "verbose_name": "Corte FONASA",
                "verbose_name_plural": "Cortes FONASA",
            },
        ),
        migrations.AlterModelOptions(
            name="hptrakcare",
            options={
                "ordering": ["run", "nombre"],
                "verbose_name": "HP Trakcare",
                "verbose_name_plural": "HP Trakcare",
            },
        ),
        migrations.AlterModelOptions(
            name="nuevousuario",
            options={
                "ordering": ["-periodo_anio", "-periodo_mes", "fecha_solicitud"],
                "verbose_name": "Nuevo Usuario",
                "verbose_name_plural": "Nuevos Usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="validacioncorte",
            options={
                "ordering": ["-periodo_anio", "-periodo_mes"],
                "verbose_name": "Validación de Corte",
                "verbose_name_plural": "Validaciones de Corte",
            },
        ),
        migrations.AddField(
            model_name="historialcarga",
            name="errores",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="cortefonasa",
            name="fecha_corte",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historialcarga",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EXITOSO", "Exitoso"),
                    ("ERROR", "Error"),
                    ("PARCIAL", "Parcial"),
                    ("EN_PROCESO", "En Proceso"),
                ],
                db_index=True,
                default="EN_PROCESO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historialcarga",
            name="periodo_anio",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historialcarga",
            name="periodo_mes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historialcarga",
            name="tiempo_procesamiento",
            field=models.FloatField(
                blank=True, help_text="Tiempo en segundos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hptrakcare",
            name="fecha_defuncion",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="hptrakcare",
            name="id_trakcare",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("VALIDADO", "Validado"),
                    ("NO_VALIDADO", "No Validado"),
                ],
                db_index=True,
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="periodo_anio",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="periodo_mes",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="validacioncorte",
            name="periodo_anio",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="validacioncorte",
            name="periodo_mes",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="historialcarga",
            index=models.Index(
                fields=["estado", "-fecha_carga"], name="api_histori_estado_effd28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validacioncorte",
            index=models.Index(
                fields=["-periodo_anio", "-periodo_mes"],
                name="api_validac_periodo_318861_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validacioncorte",
            index=models.Index(
                fields=["fecha_corte"], name="api_validac_fecha_c_d49f12_idx"
            ),
        ),
        migrations.AddField(
            model_name="cortefonasa",
            name="centro_salud",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cortes",
                to="api.centrosalud",
            ),
        ),
        migrations.AlterField(
            model_name="hptrakcare",
            name="centro_inscripcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hp_usuarios",
                to="api.centrosalud",
            ),
        ),
        migrations.AddIndex(
            model_name="cortefonasa",
            index=models.Index(
                fields=["run", "fecha_corte"], name="api_cortefo_run_074133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cortefonasa",
            index=models.Index(
                fields=["fecha_corte", "motivo_normalizado"],
                name="api_cortefo_fecha_c_98f4e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cortefonasa",
            index=models.Index(
                fields=["-fecha_corte", "centro_salud"],
                name="api_cortefo_fecha_c_88dc86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="establecimiento",
            index=models.Index(
                fields=["activo", "tipo"], name="api_estable_activo_8ac2d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="establecimiento",
            index=models.Index(
                fields=["activo", "orden"], name="api_estable_activo_07d7ab_idx"
            ),
        ),
        migrations.AddField(
            model_name="centrosalud",
            name="establecimiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="centros",
                to="api.establecimiento",
            ),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="establecimiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nuevos_usuarios",
                to="api.establecimiento",
            ),
        ),
        migrations.AddIndex(
            model_name="etnia",
            index=models.Index(
                fields=["activo", "orden"], name="api_etnia_activo_12dfd1_idx"
            ),
        ),
        migrations.AlterField(
            model_name="hptrakcare",
            name="etnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hp_usuarios",
                to="api.etnia",
            ),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="etnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nuevos_usuarios",
                to="api.etnia",
            ),
        ),
        migrations.AddIndex(
            model_name="nacionalidad",
            index=models.Index(
                fields=["activo", "orden"], name="api_naciona_activo_aa4791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nacionalidad",
            index=models.Index(
                fields=["codigo_pais"], name="api_naciona_codigo__1957d9_idx"
            ),
        ),
        migrations.AlterField(
            model_name="hptrakcare",
            name="nacionalidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hp_usuarios",
                to="api.nacionalidad",
            ),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="nacionalidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nuevos_usuarios",
                to="api.nacionalidad",
            ),
        ),
        migrations.AddIndex(
            model_name="sector",
            index=models.Index(
                fields=["activo", "orden"], name="api_sector_activo_a5132e_idx"
            ),
        ),
        migrations.AlterField(
            model_name="hptrakcare",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hp_usuarios",
                to="api.sector",
            ),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nuevos_usuarios",
                to="api.sector",
            ),
        ),
        migrations.AddIndex(
            model_name="hptrakcare",
            index=models.Index(
                fields=["run", "fecha_defuncion"], name="api_hptrakc_run_68f703_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hptrakcare",
            index=models.Index(
                fields=["id_trakcare"], name="api_hptrakc_id_trak_8f71e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hptrakcare",
            index=models.Index(
                fields=["sector", "run"], name="api_hptrakc_sector__200dc8_idx"
            ),
        ),
        migrations.AddField(
            model_name="subsector",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsectores",
                to="api.sector",
            ),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nuevos_usuarios",
                to="api.subsector",
            ),
        ),
        migrations.AddIndex(
            model_name="nuevousuario",
            index=models.Index(
                fields=["-periodo_anio", "-periodo_mes", "estado"],
                name="api_nuevous_periodo_a17886_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="centrosalud",
            index=models.Index(
                fields=["establecimiento", "activo"],
                name="api_centros_estable_25d66a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="centrosalud",
            index=models.Index(
                fields=["activo", "orden"], name="api_centros_activo_ad5c74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subsector",
            index=models.Index(
                fields=["sector", "activo"], name="api_subsect_sector__2aceb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subsector",
            index=models.Index(
                fields=["activo", "orden"], name="api_subsect_activo_45a1be_idx"
            ),
        ),
    ]
