# Generated by Django 5.2.3 on 2025-11-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_centrosalud_establecimiento_etnia_nacionalidad_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nuevousuario",
            options={
                "ordering": ["-periodo_anio", "-periodo_mes", "fecha_inscripcion"],
                "verbose_name": "Nuevo Usuario",
                "verbose_name_plural": "Nuevos Usuarios",
            },
        ),
        migrations.RenameField(
            model_name="nuevousuario",
            old_name="fecha_solicitud",
            new_name="fecha_inscripcion",
        ),
    ]
