# Generated by Django 5.2.3 on 2025-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_fecha_solicitud_to_inscripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="nuevousuario",
            name="apellido_materno",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="nuevousuario",
            name="apellido_paterno",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="nuevousuario",
            name="centro",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="nuevousuario",
            name="codigo_sector",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="nuevousuario",
            name="nombres",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="codigo_percapita",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="nombre_completo",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
