# Generated by Django 5.2.3 on 2025-11-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_nuevos_usuarios_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cortefonasa",
            name="aceptado_rechazado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACEPTADO", "Aceptado"),
                    ("RECHAZADO", "Rechazado"),
                    ("", "No especificado"),
                ],
                default="",
                help_text="Estado de aceptación o rechazo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cortefonasa",
            name="centro_actual",
            field=models.CharField(
                blank=True, help_text="Centro de salud actual/destino", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="cortefonasa",
            name="centro_de_procedencia",
            field=models.CharField(
                blank=True, help_text="Centro de salud de origen", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="cortefonasa",
            name="comuna_actual",
            field=models.CharField(
                blank=True, help_text="Comuna actual/destino", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="cortefonasa",
            name="comuna_de_procedencia",
            field=models.CharField(
                blank=True, help_text="Comuna de origen", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="nuevousuario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("VALIDADO", "Validado"),
                    ("NO_VALIDADO", "No Validado"),
                    ("FALLECIDO", "Fallecido"),
                ],
                db_index=True,
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
