# Generated by Django 5.2.3 on 2025-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_add_centro_procedencia_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cortefonasa",
            name="aceptado_rechazado",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Estado de aceptación o rechazo",
                max_length=255,
            ),
        ),
    ]
