# Generated by Django 5.2.3 on 2025-11-07 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_actualizar_subsectores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("nombre_completo", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("es_admin", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                (
                    "creado_el",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modificado_el", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["username"],
            },
        ),
        migrations.RemoveField(
            model_name="centrosalud",
            name="establecimiento",
        ),
        migrations.AlterField(
            model_name="cortefonasa",
            name="centro_salud",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cortes",
                to="api.establecimiento",
            ),
        ),
        migrations.AlterField(
            model_name="hptrakcare",
            name="centro_inscripcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hp_usuarios",
                to="api.establecimiento",
            ),
        ),
        migrations.AlterModelOptions(
            name="establecimiento",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Establecimiento",
                "verbose_name_plural": "Establecimientos",
            },
        ),
        migrations.AlterModelOptions(
            name="etnia",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Etnia",
                "verbose_name_plural": "Etnias",
            },
        ),
        migrations.AlterModelOptions(
            name="nacionalidad",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Nacionalidad",
                "verbose_name_plural": "Nacionalidades",
            },
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectores",
            },
        ),
        migrations.AlterModelOptions(
            name="subsector",
            options={
                "ordering": ["codigo", "nombre"],
                "verbose_name": "Subsector",
                "verbose_name_plural": "Subsectores",
            },
        ),
        migrations.RemoveIndex(
            model_name="establecimiento",
            name="api_estable_activo_8ac2d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="establecimiento",
            name="api_estable_activo_07d7ab_idx",
        ),
        migrations.RemoveIndex(
            model_name="etnia",
            name="api_etnia_activo_12dfd1_idx",
        ),
        migrations.RemoveIndex(
            model_name="nacionalidad",
            name="api_naciona_activo_aa4791_idx",
        ),
        migrations.RemoveIndex(
            model_name="nacionalidad",
            name="api_naciona_codigo__1957d9_idx",
        ),
        migrations.RemoveIndex(
            model_name="sector",
            name="api_sector_activo_a5132e_idx",
        ),
        migrations.RemoveIndex(
            model_name="subsector",
            name="api_subsect_sector__2aceb4_idx",
        ),
        migrations.RemoveIndex(
            model_name="subsector",
            name="api_subsect_activo_45a1be_idx",
        ),
        migrations.RemoveField(
            model_name="cortefonasa",
            name="cod_genero",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="comuna",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="creado_el",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="email",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="modificado_el",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="region",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="telefono",
        ),
        migrations.RemoveField(
            model_name="establecimiento",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="etnia",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="etnia",
            name="creado_el",
        ),
        migrations.RemoveField(
            model_name="etnia",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="etnia",
            name="modificado_el",
        ),
        migrations.RemoveField(
            model_name="etnia",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="nacionalidad",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="nacionalidad",
            name="codigo_pais",
        ),
        migrations.RemoveField(
            model_name="nacionalidad",
            name="creado_el",
        ),
        migrations.RemoveField(
            model_name="nacionalidad",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="nacionalidad",
            name="modificado_el",
        ),
        migrations.RemoveField(
            model_name="nacionalidad",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="color",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="creado_el",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="modificado_el",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="subsector",
            name="color",
        ),
        migrations.RemoveField(
            model_name="subsector",
            name="creado_el",
        ),
        migrations.RemoveField(
            model_name="subsector",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="subsector",
            name="modificado_el",
        ),
        migrations.RemoveField(
            model_name="subsector",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="subsector",
            name="sector",
        ),
        migrations.AddIndex(
            model_name="establecimiento",
            index=models.Index(fields=["activo"], name="api_estable_activo_1b205e_idx"),
        ),
        migrations.AddIndex(
            model_name="etnia",
            index=models.Index(fields=["activo"], name="api_etnia_activo_b92959_idx"),
        ),
        migrations.AddIndex(
            model_name="nacionalidad",
            index=models.Index(fields=["activo"], name="api_naciona_activo_9bec17_idx"),
        ),
        migrations.AddIndex(
            model_name="sector",
            index=models.Index(fields=["activo"], name="api_sector_activo_24accd_idx"),
        ),
        migrations.AddIndex(
            model_name="subsector",
            index=models.Index(fields=["activo"], name="api_subsect_activo_951ea1_idx"),
        ),
        migrations.AddIndex(
            model_name="subsector",
            index=models.Index(fields=["codigo"], name="api_subsect_codigo_7329ed_idx"),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["username"], name="api_usuario_usernam_5e8ebc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["activo"], name="api_usuario_activo_701f84_idx"),
        ),
        migrations.DeleteModel(
            name="CentroSalud",
        ),
    ]
