# Generated by Django 5.2.7 on 2025-11-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_unique_together_cortefonasa"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorteFonasaObservacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("estado_revision", models.CharField(choices=[("PENDIENTE", "Pendiente"), ("CONTACTADO", "Contactado"), ("AGENDADO", "Agendado"), ("RESUELTO", "Resuelto"), ("NO_LOCALIZADO", "No localizado")], db_index=True, default="PENDIENTE", max_length=20)),
                ("tipo", models.CharField(choices=[("PREDEFINIDA", "Predefinida"), ("MANUAL", "Manual")], default="PREDEFINIDA", max_length=20)),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("texto", models.TextField(blank=True)),
                ("adjunto", models.FileField(blank=True, null=True, upload_to=api.models.observacion_upload_to)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("autor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="observaciones_cortes", to=settings.AUTH_USER_MODEL)),
                ("corte", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observaciones", to="api.cortefonasa")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cortefonasaobservacion",
            index=models.Index(fields=["corte", "-created_at"], name="api_cortef_corte__356605_idx"),
        ),
        migrations.AddIndex(
            model_name="cortefonasaobservacion",
            index=models.Index(fields=["estado_revision", "corte"], name="api_cortef_estador_76c391_idx"),
        ),
    ]
