# Generated by Django 5.2.3 on 2025-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_cortefonasaobservacion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cortefonasaobservacion",
            new_name="api_cortefo_corte_i_f9bf20_idx",
            old_name="api_cortef_corte__356605_idx",
        ),
        migrations.RenameIndex(
            model_name="cortefonasaobservacion",
            new_name="api_cortefo_estado__1f538e_idx",
            old_name="api_cortef_estador_76c391_idx",
        ),
        migrations.AddField(
            model_name="cortefonasaobservacion",
            name="autor_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre o RUT del usuario que creó la observación",
                max_length=255,
            ),
        ),
    ]
