# Generated by Django 5.2.3 on 2025-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0017_rename_api_cortef_corte__356605_idx_api_cortefo_corte_i_f9bf20_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cortefonasa",
            name="nombre_centro_actual",
            field=models.CharField(
                blank=True, help_text="Nombre del centro actual/destino", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="cortefonasa",
            name="rut_centro_actual",
            field=models.CharField(
                blank=True, help_text="RUT del centro actual/destino", max_length=12
            ),
        ),
        migrations.AddField(
            model_name="cortefonasa",
            name="rut_centro_procedencia",
            field=models.CharField(
                blank=True, help_text="RUT del centro de procedencia", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="cortefonasa",
            name="centro_actual",
            field=models.CharField(
                blank=True,
                help_text="Centro de salud actual/destino (legacy)",
                max_length=255,
            ),
        ),
    ]
