# Generated by Django 5.2.3 on 2025-11-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_cortefonasa_nombre_centro_actual_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cortefonasa",
            name="rut_centro_actual",
        ),
        migrations.RemoveField(
            model_name="cortefonasa",
            name="rut_centro_procedencia",
        ),
    ]
